json.extract! plan,
              :id,
              :planned_type,
              :planned_id,
              :begin_on,
              :end_on,
              :place_id,
              :repeat_type,
              :repeat_days,
              :updated_at
